In [106]:
# docker build -t external_indexing_2 .
# docker run -it --name my-container_50 -v C:\repos\external_indexing_3\danfcontainerformat\data:/app/data external_indexing_2
# Online Jupyter notebook https://www.kaggle.com/code

# Dictionary

# Initializing a dict
name = 'name'
foot_size = 4
dict_a={name:'Mark', 4:4, 'foot_size':str(foot_size)}
print(dict_a)

# Adding one key:value pair if not exists
dict_a.setdefault('height', 175)
dict_a.setdefault('name', 'David')
print(dict_a)

# Adding multiple key:value pairs, even if exists (overwritten)
dict_b = {'age': 31, 'weight': 75, 'height': 180}
dict_a.update(dict_b)
print(dict_a)

# Merging 2 dictionaries, 1st stronger
dict_c={'eyecolor':'blue', 'weight' : 90}
dict_d={**dict_a, **dict_c}
print(dict_d)

# Getting a value by "get"
print(dict_d.get('name'), dict_d.get('names'), dict_d['name'])

# in / not in 
print('name' in dict_d.keys())
print('name' in dict_d.values())
print(f"The key 'name' is present in the dictionary: {'name' in dict_d.keys()}","PLUS",'name' in dict_d.keys())

# loop
for dict_element in dict_d.items():
    print(dict_element)
    print(f'Hello {type(dict_element)} and {2+4}')
    break

for dict_element in dict_d:
    print(dict_element)
    break

for dict_element in dict_d.keys():
    print(dict_element)
    break

for dict_element in dict_d.values():
    print(dict_element)
    break

{'name': 'Mark', 4: 4, 'foot_size': '4'}
{'name': 'Mark', 4: 4, 'foot_size': '4', 'height': 175}
{'name': 'Mark', 4: 4, 'foot_size': '4', 'height': 180, 'age': 31, 'weight': 75}
{'name': 'Mark', 4: 4, 'foot_size': '4', 'height': 180, 'age': 31, 'weight': 90, 'eyecolor': 'blue'}
Mark None Mark
True
False
The key 'name' is present in the dictionary: True PLUS True
('name', 'Mark')
Hello <class 'tuple'> and 6
name
name
Mark

In [89]:
# set - unique, unordered collection

# create a set, like a dictionary
set_a = {1,2,3,'Mark'}
print(set_a)

# adding an element to a set, only if not exists
set_a.add(4)
print(set_a)

# updating it with multiple elements
set_a.update([3, 5, 6])
print(set_a)

# removing an element
set_a.remove(5) # keyError if not found
set_a.discard(5) # no Error if not found 
# .clear() delete all elements
print(set_a)

set_b = {1,2,3}

union_set = set_a | set_b
difference_set = set_a - set_b
intersection_set = set_a & set_b

print(f'set_a {set_a}')
print(f'set_b {set_b}')
print(f'union set {union_set}')
print(f'difference set {difference_set}')
print(f'intersection set {intersection_set}')

{1, 2, 3, 'Mark'}
{1, 2, 3, 4, 'Mark'}
{1, 2, 3, 4, 5, 6, 'Mark'}
{1, 2, 3, 4, 6, 'Mark'}
set_a {1, 2, 3, 4, 6, 'Mark'}
set_b {1, 2, 3}
union set {1, 2, 3, 4, 6, 'Mark'}
difference set {4, 'Mark', 6}
intersection set {1, 2, 3}

In [104]:
# Function
# Function definition with typecheck - raise Error if not proper
def add (n:int=0, m:int=0)->int:
    if not isinstance(n, int):
        raise TypeError("n must be an int")
    if not isinstance(m, int) or m < 0:
        raise ValueError("m must be a non-negative integer")
    return n+m


# try - catch block
try:
    print(add(3,4))
    print(add(4))
    print(add(4.5))
except (TypeError, ValueError) as e:
    print(f"Validation Error: {e}")

    
# Lambda function examples
def make_adder(n):
    return lambda x: x+n
adder_3 = make_adder(3)
print(adder_3(4))

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)

numbers = [1, 2, 3, 4, 5]
squared_numbers=list(map(lambda x: x**2, numbers))
print(squared_numbers)

numbers = [1, 2, 3, 4, 5]
result = list(map(lambda x: x**2 if x%2==0 else x, numbers))
print(result)

7
4
Validation Error: n must be an int
7
[2, 4, 6, 8, 10]
[1, 4, 9, 16, 25]
Addition: 8
[1, 4, 3, 16, 5]

In [ ]:
# Classes - OOP
# Docstring document - what, why, subtasks (functions, entites)

# Entites (nouns or action_managers)
# Attributes of them (id, name, description, created_at, last_touched, state (mode), flags, related objects (List of them, only one), config in configurable)
    # tags (organizing),  owner created, url, custom (can be anything to make it flexible)
# Methods (init, set, get, validatiton, action (start), iter to make it iterable, adding removing to/from list ...) any return value
    # verbs
# inheritence (is-a) / aggregation (has-a-outside-init) / composition (has-a-inside-init)

from abc import ABC, abstractmethod
# pydantic | BaseModel can be used - DataModel class initilaized as attribute for another class
from typing import List

class Person:
    def __init__(self, name: str) -> None:
        self.name = name
        self.books_rented: List[Book] = []
    

    def rent_a_book(self, book: Book) -> None:
        self.books_rented.append(book)
        book.is_rented = True
        book.renter = self

    def derent_a_book(self, book: Book) -> None:
        self.books_rented.remove(book)
        book.is_rented = False
        book.renter = None

class Item:
    def __init__(self, color: str) -> None:
        self.color = color

class Book(Item):
    def __init__(self, title: str, pages: int) -> None:
        self._title = title
        self._pages = pages
        self._renter = None
        self._is_rented = False
        self._content: List[str] = []

    @property
    def title(self):
        return self._title

    @property
    def pages(self):
        return self._pages

    @property
    def is_rented(self):
        return self._is_rented

    @property
    def renter(self):
        return self._renter

    @renter.setter
    def renter(self, renter):
        # Add logic to ensure renter is an instance of Person
        if isinstance(renter, Person):
            self._renter = renter
        else:
            raise ValueError("Renter must be an instance of Person.")

    @is_rented.setter
    def is_rented(self, is_rented):
        self._is_rented = is_rented

    @title.setter
    def title(self, title):
        self._title = title

    @pages.setter
    def pages(self, pages):
        # Add logic to ensure pages is a positive integer
        if isinstance(pages, int) and pages > 0:
            self._pages = pages
        else:
            raise ValueError("Pages must be a positive integer.")
   
    
    def is_composite():
        return False

book = Book(title='title', pages=232)
print(type(book.pages))  # Access the 'pages' property without using ()
print(type(book.pages))  # Access the 'pages' property without using ()

# ploymorphism (multiple type - parent, useful for function writing only for a common parent)
# inheritance (common attributes can be collected to a pranet)
# encapsulation - related data and methods for managing that data is at one place
# override

In [ ]:
# Pydantic is a data validation and parsing library in Python for validating 
# pip install pydantic

from pydantic import BaseModel
from typing import List

class Person(BaseModel):
    name: str
    age: int

# Valid data
valid_data = {"name": "John Doe", "age": 25}
person = Person(**valid_data)
print(person)




class Book(BaseModel):
    title: str
    pages: int

class LibraryBook:
    def __init__(self, title, pages):
        self.book_data = Book(title=title, pages=pages)

    def display_info(self):
        print(f"Title: {self.book_data.title}, Pages: {self.book_data.pages}")

# Create an instance of the traditional class with Pydantic BaseModel
library_book = LibraryBook(title='Example Title', pages=200)

# Access and display information using the class method
library_book.display_info()

In [7]:
# Comprehension

# List
squares = [x**2 for x in range(10)]
print(squares)

evens = [x for x in range(10) if x % 2 == 0]
print(evens)

values = [1, -2, 3, -4, 5]
absolute_values = [abs(x) if x > 0 else 0 for x in values]


words = ["hello", "world", "python"]
uppercase_words = [word.upper() for word in words]
print(uppercase_words)

original_dict = {'a': 3, 'b': 8, 'c': 5}
filtered_dict = {key+' square': value*2 for key, value in original_dict.items() if value > 5}
print(filtered_dict)


square_generator = (x**2 for x in range(10))
print(next(square_generator))  # Output: 0
print(next(square_generator))  # Output: 1
print(next(square_generator))  # Output: 4
print(next(square_generator))  # Output: 9
print(next(square_generator))  # Output: 16

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8]
['HELLO', 'WORLD', 'PYTHON']
{'b square': 16}
0
1
4
9
16

In [10]:
# Exception

try:
    num = int(input("Enter a number: "))
    result = 10 / num
except ValueError:
    print("Error: Invalid input, please enter a number.")
except ZeroDivisionError:
    print("Error: Division by zero")

# FileNotFoundError - with open
# IndexError - working with list and indexes
# KeyError - wirking with dictironaries
# ZeroDivisionError - having division calculation
# AttributeError - working with class attributes
# ImportError - importing modules
# json.JSONDecodeError - loading and dumping json
# ValueError - Input, dataconversion
# TypeError - not good data type

try:
    age = int(input("Enter your age: "))
    if age < 0:
        raise ValueError("Age cannot be negative")
except ValueError as ve:
    print(f"Error: {ve}")

Enter a number: 2
Enter your age: -1
Error: Age cannot be negative

In [3]:
# Arg/Kwargs
# allows for a flexible and extensible function that can process various types of data with additional contextual information
# multi purpose function - general function to be defined, based on what is passed a part can be executed

# Function with a variable number of positional arguments:
def print_args(*args):
    for arg in args:
        print(arg)

print_args(1, 2, 3, "four",5)


# Function with a variable number of keyword arguments:
def print_kwargs(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

print_kwargs(name="John", age=25, city="New York")

# user-friendly APIs, for decorator function, for modyfiing a function definition without modyfiing all the call on the client side - just add *args and **kwargs
# more difficult to test the dynamic nature of it, worse performance

1
2
3
four
5
name: John
age: 25
city: New York

In [8]:
# Regex, Generator

import re

string = 'http://localhost:8888/notebooks/python_basics.ipynb'

result = re.compile(r'(.*)/(.*).ipynb').search(string).group(2)
print(result)

python_basics

error: unbalanced parenthesis at position 13

In [17]:
import pandas as pd


data = [
    {'Name': 'Alice', 'Age': 28, 'Gender': 'Female', 'Occupation': 'Engineer', 'Salary': 80000, 'Location': 'New York', 'Education': "Master's", 'MaritalStatus': 'Single'},
    {'Name': 'Bob', 'Age': 35, 'Gender': 'Male', 'Occupation': 'Doctor', 'Salary': 120000, 'Location': 'Los Angeles', 'Education': 'PhD', 'MaritalStatus': 'Married'},
    {'Name': 'Charlie', 'Age': 40, 'Gender': 'Male', 'Occupation': 'Teacher', 'Salary': 60000, 'Location': 'San Francisco', 'Education': "Bachelor's", 'MaritalStatus': 'Single'},
    {'Name': 'David', 'Age': 32, 'Gender': 'Male', 'Occupation': 'Data Scientist', 'Salary': 95000, 'Location': 'Chicago', 'Education': "Master's", 'MaritalStatus': 'Married'},
    {'Name': 'Eva', 'Age': 27, 'Gender': 'Female', 'Occupation': 'Designer', 'Salary': 70000, 'Location': 'Miami', 'Education': "Bachelor's", 'MaritalStatus': 'Single'},
    {'Name': 'Frank', 'Age': 45, 'Gender': 'Male', 'Occupation': 'Manager', 'Salary': 110000, 'Location': 'Dallas', 'Education': 'PhD', 'MaritalStatus': 'Married'},
    {'Name': 'Grace', 'Age': 33, 'Gender': 'Female', 'Occupation': 'Software Engineer', 'Salary': 85000, 'Location': 'Boston', 'Education': "Master's", 'MaritalStatus': 'Single'},
    {'Name': 'Hank', 'Age': 39, 'Gender': 'Male', 'Occupation': 'Lawyer', 'Salary': 100000, 'Location': 'Seattle', 'Education': 'JD', 'MaritalStatus': 'Married'},
    {'Name': 'Ivy', 'Age': 31, 'Gender': 'Female', 'Occupation': 'Marketing Specialist', 'Salary': 75000, 'Location': 'Austin', 'Education': "Bachelor's", 'MaritalStatus': 'Single'},
    {'Name': 'Jack', 'Age': 29, 'Gender': 'Male', 'Occupation': 'Financial Analyst', 'Salary': 90000, 'Location': 'Denver', 'Education': "Master's", 'MaritalStatus': 'Married'},
]


# Convert the list of dictionaries to a pandas DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)




# Creating DataFrames
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Salary': [50000, 60000, 75000]}
df = pd.DataFrame(data)

# Reading from CSV and Excel files
# Uncomment the line below if you have a CSV file
# df_csv = pd.read_csv('your_file.csv')
# Uncomment the line below if you have an Excel file
# df_excel = pd.read_excel('your_file.xlsx')

# Viewing Data
print("First 2 rows:")
print(df.head(2))
print("\nLast 2 rows:")
print(df.tail(2))
print("\nDataFrame Information:")
print(df.info())
print("\nDescriptive Statistics:")
print(df.describe())

# Selecting Data
print("\nSelecting a single column:")
print(df['Name'])
print("\nSelecting multiple columns:")
print(df[['Name', 'Age']])
print("\nSelecting rows and columns by label:")
print(df.loc[0:2, 'Name'])
print("\nSelecting rows and columns by position:")
print(df.iloc[0, 0])



# Filtering Data
print("\nFiltering rows based on a condition:")
print(df[df['Age'] > 30]) # selecting where age > 30
print("\nAnother way to filter rows based on a condition:")
print(df.query('Age > 30'))
#  filtered_df = df[(df['Age'] > 30) & (df['City'] == 'New York')]
# cities_to_keep = ['New York', 'Chicago']
# filtered_df = df[df['City'].isin(cities_to_keep)]


# Handling Missing Data
print("\nChecking for missing values:")
print(df.isnull())
print("\nDropping rows with missing values:")
print(df.dropna())
# Drop columns with any missing values
df_dropna_columns = df.dropna(axis=1)
print("\nFilling missing values:")
print(df.fillna(0))
df_dropped = df.dropna(subset=['Age'])

# Grouping and Aggregating
print("\nGrouping and calculating mean:")
print(df.groupby('Age').mean())
print("\nGrouping and aggregating with multiple functions:")
print(df.groupby('Age').agg({'Salary': 'sum', 'Name': 'count'}))
# Create a sample DataFrame
data = {'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
        'Value': [10, 20, 15, 25, 12, 18],
        'Quantity': [5, 8, 6, 9, 4, 7]}
df = pd.DataFrame(data)
grouped = df.groupby('Category')
# Calculate the mean for each group
mean_values = grouped.mean()
# Sum of values in each group
sum_values = grouped['Value'].sum()
# Count of rows in each group
count_values = grouped.size()
# Maximum value in each group
max_values = grouped['Value'].max()
# Applying multiple aggregation functions
agg_result = grouped.agg({'Value': 'mean', 'Quantity': 'sum'})



# Sorting Data
print("\nSorting by values:")
print(df.sort_values('Age'))
print("\nSorting by index:")
print(df.sort_index())
# sorted_df = df.sort_values(by=['Category', 'Value'])
# sorted_df_descending = df.sort_values(by=['Category', 'Value'], ascending=[True, False])


# Combining DataFrames
# Uncomment the lines below to see examples of concatenation and merging
# df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']}, index=[0, 1])
# df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']}, index=[2, 3])
# print("\nConcatenating DataFrames:")
# print(pd.concat([df1, df2], axis=0)) # putting next to each other (1) / on top (0)
# print("\nMerging DataFrames:")
# print(pd.merge(df1, df2, on='A')) # merging together along a common value

# Changing Data in a oclumn
df['Age'] = [26, 31, 36]
# Adding a new column 'AgeAfterBirthday'
df['AgeAfterBirthday'] = df['Age'] + 1
# Replacing 'Bob' with 'Robert' in the 'Name' column
df['Name'].replace('Bob', 'Robert', inplace=True)
# Filling missing values in the 'Age' column with the mean
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Age'] = df['Age'].apply(add_one)
print("\nApplying a function to a column:")
df['Salary'] = df['Salary'].apply(lambda x: x + 1000)
print(df['Salary'])
print("\nRenaming columns:")
df.rename(columns={'Name': 'FullName', 'Age': 'Years'}, inplace=True)
print(df.columns)
print("\nDropping columns:")
df.drop(['Years', 'Salary'], axis=1, inplace=True)
print(df.columns)

# Statistics
print("\nCalculating mean, median, and standard deviation:")
print(df.mean())
print(df.median())
print(df.std())
print("\nCalculating pairwise correlation of columns:")
print(df.corr())


# Perform an inner join on the 'ID' column
df_joined = pd.merge(df_table1, df_table2, on='ID', how='inner')



# CSV
# Read the CSV file into a DataFrame
# df = pd.read_csv('example.csv')

# SQL query
import sqlite3
# Connect to the SQLite database
# conn = sqlite3.connect('your_database.db')
# Connect to the MySQL database
#conn = mysql.connector.connect(
#    host='your_mysql_host',
#    user='your_username',
#    password='your_password',
#    database='your_database'
#)
# Write a SQL query to select data from a table
# sql_query = "SELECT * FROM your_table"
# Use pandas to read data from the SQL query result into a DataFrame
# df = pd.read_sql(sql_query, conn)
# Close the database connection
# conn.close()

# SQL table
import sqlalchemy
# Replace the following connection string with your database details
# For example, for SQLite: 'sqlite:///your_database.db'
# For MySQL or PostgreSQL: 'mysql://your_username:your_password@your_mysql_host/your_database'
# or 'postgresql://your_username:your_password@your_postgresql_host/your_database'
# db_connection_string = 'your_database_connection_string'
# Create an SQLAlchemy engine
# engine = sqlalchemy.create_engine(db_connection_string)
# Replace 'your_table' with the name of the table you want to read
# table_name = 'your_table'
# Use pandas to read the entire table into a DataFrame
# df = pd.read_sql_table(table_name, con=engine)
# Display the DataFrame
# print(df)

      Name  Age  Gender            Occupation  Salary       Location  \
0    Alice   28  Female              Engineer   80000       New York
1      Bob   35    Male                Doctor  120000    Los Angeles
2  Charlie   40    Male               Teacher   60000  San Francisco
3    David   32    Male        Data Scientist   95000        Chicago
4      Eva   27  Female              Designer   70000          Miami
5    Frank   45    Male               Manager  110000         Dallas
6    Grace   33  Female     Software Engineer   85000         Boston
7     Hank   39    Male                Lawyer  100000        Seattle
8      Ivy   31  Female  Marketing Specialist   75000         Austin
9     Jack   29    Male     Financial Analyst   90000         Denver

    Education MaritalStatus
0    Master's        Single
1         PhD       Married
2  Bachelor's        Single
3    Master's       Married
4  Bachelor's        Single
5         PhD       Married
6    Master's        Single
7          JD       Married
8  Bachelor's        Single
9    Master's       Married
First 2 rows:
    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000

Last 2 rows:
      Name  Age  Salary
1      Bob   30   60000
2  Charlie   35   75000

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes
None

Descriptive Statistics:
        Age        Salary
count   3.0      3.000000
mean   30.0  61666.666667
std     5.0  12583.057392
min    25.0  50000.000000
25%    27.5  55000.000000
50%    30.0  60000.000000
75%    32.5  67500.000000
max    35.0  75000.000000

Selecting a single column:
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

Selecting multiple columns:
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

Selecting rows and columns by label:
Alice

Selecting rows and columns by position:
Alice

Filtering rows based on a condition:
      Name  Age  Salary
2  Charlie   35   75000

Another way to filter rows based on a condition:
      Name  Age  Salary
2  Charlie   35   75000

Checking for missing values:
    Name    Age  Salary
0  False  False   False
1  False  False   False
2  False  False   False

Dropping rows with missing values:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000

Filling missing values:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000

Grouping and calculating mean:
      Salary
Age
25   50000.0
30   60000.0
35   75000.0

Grouping and aggregating with multiple functions:
     Salary  Name
Age
25    50000     1
30    60000     1
35    75000     1

Sorting by values:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000

Sorting by index:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000

Applying a function to a column:
0    51000
1    61000
2    76000
Name: Salary, dtype: int64

Renaming columns:
Index(['FullName', 'Years', 'Salary'], dtype='object')

Dropping columns:
Index(['FullName'], dtype='object')

Calculating mean, median, and standard deviation:
Series([], dtype: float64)
Series([], dtype: float64)
Series([], dtype: float64)

Calculating pairwise correlation of columns:
Empty DataFrame
Columns: []
Index: []
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000

C:\cygwin64\tmp\ipykernel_26272\4136967231.py:147: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.mean())
C:\cygwin64\tmp\ipykernel_26272\4136967231.py:148: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.median())
C:\cygwin64\tmp\ipykernel_26272\4136967231.py:149: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.std())

In [12]:
# Lists

my_list = ['name', 2, 3.5]
print(my_list[0])
print(my_list[-1])
print(my_list[0:1])
print(my_list[:-2])

my_list.append(3)
my_list.remove(2)

try:
    my_list.remove(25)
except ValueError as e:
    print (e)
    
print(my_list.index(3))
print(my_list)
my_list.insert(1,'A')
print(my_list)

print ('nam' in my_list)
print ('name' in my_list)

for index,element in enumerate(my_list):
    print(f"The {index} element is {element}")

my_list_2=my_list

for element_1,element_2 in zip(my_list, my_list_2):
    print(f"Element A {element_1} Element B {element_2}")

name
3.5
['name']
['name']
list.remove(x): x not in list
2
['name', 3.5, 3]
['name', 'A', 3.5, 3]
False
True
The 0 element is name
The 1 element is A
The 2 element is 3.5
The 3 element is 3
Element A name Element B name
Element A A Element B A
Element A 3.5 Element B 3.5
Element A 3 Element B 3

['This', 'is', 'a', 'sentence']

TypeError: slice indices must be integers or None or have an __index__ method

In [19]:
import pandas as pd

# Create a sample DataFrame
data = {'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
        'Value': [10, 20, 15, 25, 12, 18],
        'Quantity': [5, 8, 6, 9, 4, 7]}
df = pd.DataFrame(data)

# Group by 'Category' and aggregate with different functions for each column
result = df.groupby('Category').agg({'Value': 'mean', 'Quantity': 'sum'}).reset_index()

# Display the result
print(result)

  Category      Value  Quantity
0        A  12.333333        15
1        B  21.000000        24